version: '2.1'
orbs:
  unity: game-ci/unity@1.7.0 
workflows:
  create-unity-activation-file:
    jobs:
     - unity/build:
          name: "build-webgl"
          step-name: "Build WebGL"
          unity-license-var-name: "UNITY_ENCODED_LICENSE"
          unity-username-var-name: "UNITY_USERNAME"
          unity-password-var-name: "UNITY_PASSWORD"
          executor:
            name: "unity/ubuntu"
            target_platform: "webgl"
            editor_version: "2021.3.9f1"
            resource_class: "large"
          project-path: "src"
          build-target: "WebGL"
          # Since "Compression Format" is set to disabled in Unity,
          # if we set "compress" to false, we can play the game from
          # the CircleCI web app by going in the "Artifacts" tab.
          compress: false
          context: cpe-unity